# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json

package: "api"
output: "./pkg/api/generated/api-gateway/gen.go"
generate:
  gorilla-server: true

  client: true
  models: true
compatibility:
  apply-gorilla-middleware-first-to-last: true
