basePath: /auth
info:
  contact:
    email: platform-team@myorg.io
    name: platform-team
  description: Authentication service for payloads
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: IDP Auth-Service
  version: "1.0"
paths: {}
swagger: "2.0"
