basePath: /api/v1
info:
  contact:
    email: platform-team@myorg.io
    name: plateform-team
  description: Entry point for all the clients and cli
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: IDP API Gateway
  version: "1.0"
paths:
  /healthz:
    get:
      responses:
        "200":
          description: OK
      summary: health of the server handler
  /ready:
    get:
      responses:
        "200":
          description: OK
      summary: readyness of the server
swagger: "2.0"
