# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: apiAuth
generate:
  # NOTE another server must be added!
  gorilla-server: true

  models: true
  client: true
output: "./pkg/api/generated/auth-service/gen.go"
output-options:
  name-normalizer: ToCamelCase
  skip-prune: true
